name: Lint

on:
  workflow_call:
    secrets:
      API_KEY:
        required: true

permissions:
  statuses: none
  contents: read
  checks: write

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.3'

      - name: Setup ReviewDog
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Restore gradle cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle', '**/*.gradle.kts') }}

      - name: Create local.properties
        run: echo "API_KEY=${{ secrets.API_KEY }}" > local.properties

      - name: Run lint
        id: lint
        continue-on-error: true
        run: ./gradlew lint

      - name: Run report with ReviewDog
        if: failure()
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: cat ./build/reports/lint-results.xml | reviewdog -f=checkstyle -name="lint" -reporter="github-pr-review"

      - name: Comment lint check success
        if: success()
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: lint
          recreate: true
          message: |
            :sparkles: :sparkles: **Perfect! Passed the PR lint check successfully!** :sparkles: :sparkles:
