name: CI

on:
  pull_request:
    branches: [ "master", "developer" ]
    types: [ opened, synchronize ]

  # openedのトリガーで呼ばれないため、workflow_runを追加
  workflow_run:
    workflows: [ "Create Pull Request" ]
    types:
      - completed

# 並行処理の設定
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: true

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  PullRequestCheck:
    uses: ./.github/workflows/call-pull-request-check.yml
    secrets:
      API_KEY: ${{ secrets.API_KEY }}

  UnitTests:
    uses: ./.github/workflows/call-unit-test.yml
    secrets:
      API_KEY: ${{ secrets.API_KEY }}