name: CI

on:
  push:
    branches: [ "developer" ]
  pull_request:
    branches: [ "developer" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: true

permissions:
  checks: write
  contents: read

jobs:
  Lint:
    uses: ./.github/workflows/call-lint.yml
    secrets:
      API_KEY: ${{ secrets.API_KEY }}
  unit_tests:
    uses: ./.github/workflows/call-unit-test.yml
    secrets:
      API_KEY: ${{ secrets.API_KEY }}